//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebasUnitarias.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PruebasUnitarias.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1143875490;12 nov 2019 2:00 pm;2;icesi;calima;1
        ///1143444502
        ///1155767890;11 nov 2018 3:00 pm;3;icesi;valledellili;2
        ///1133567890
        ///1143875490.
        /// </summary>
        internal static string Servicios {
            get {
                return ResourceManager.GetString("Servicios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sarai;4467582;1143875490;holamundo;USUARIO_SIN_CARRO;0;2
        ///12 enero 2017 3:55 pm;1;icesi;chipichape
        ///13 diciembre 2017 4:00 pm;1;chipichape;icesi
        ///leslie;3128762;1143444502;holi;USUARIO_CON_CARRO;1;3
        ///mazda;aup999;gris
        ///4 febrero 2017 2:00 pm;2;calima;icesi
        ///4 febrero 2017 8:00 pm;3;icesi;hacienda
        ///5 febrero 2017 7:00 am;4;chiminangos;icesi
        ///Valery;4556790;1133567890;no;USUARIO_SIN_CARRO;0;2
        ///12 febrero 2017 4:55 pm;1;icesi;la70
        ///13 marzo 2017 4:00 pm;1;la70;icesi
        ///Victor;4778939;1155767890;no;USUARIO_CON_CA [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Usuarios {
            get {
                return ResourceManager.GetString("Usuarios", resourceCulture);
            }
        }
    }
}
